import type { ComponentProps } from "react";
import SettingsPanel from "../components/SettingsPanel";
import type { AppState } from "../../app/types";
import type { Locale } from "../../../shared/types";

type SettingsPanelProps = ComponentProps<typeof SettingsPanel>;

interface UseSettingsPanelPropsOptions {
  t: (key: string) => string;
  theme: string;
  language: Locale;
  colorMode: string;
  hotkeyParts: string[];
  checkHotkeyConflict: (newHotkey: string, mode: "main" | "sequential" | "rich" | "search") => boolean;
  updateHotkey: (key: string) => void;
  updateRichPasteHotkey: (key: string) => void;
  updateSearchHotkey: (key: string) => void;
  updateSequentialHotkey: (key: string) => void;
  saveAppSetting: (key: string, val: string) => void;
  saveSetting: (key: string, val: string) => void;
  handleResetSettings: () => void;
  toggleGroup: (group: string) => void;
  state: AppState;
}

export const useSettingsPanelProps = ({
  t,
  theme,
  language,
  colorMode,
  hotkeyParts,
  checkHotkeyConflict,
  updateHotkey,
  updateRichPasteHotkey,
  updateSearchHotkey,
  updateSequentialHotkey,
  saveAppSetting,
  saveSetting,
  handleResetSettings,
  toggleGroup,
  state
}: UseSettingsPanelPropsOptions): SettingsPanelProps => {
  const {
    collapsedGroups,
    settingsSubpage,
    setSettingsSubpage,
    autoStart,
    silentStart,
    persistent,
    persistentLimitEnabled,
    persistentLimit,
    deduplicate,
    captureFiles,
    captureRichText,
    richTextSnapshotPreview,
    deleteAfterPaste,
    moveToTopAfterPaste,
    richPasteHotkey,
    isRecordingRich,
    searchHotkey,
    isRecordingSearch,
    quickPasteModifier,
    setQuickPasteModifier,
    cleanupRules,
    setCleanupRules,
    appCleanupPolicies,
    setAppCleanupPolicies,
    hotkey,
    showHotkeyHint,
    showSearchBox,
    setShowSearchBox,
    scrollTopButtonEnabled,
    setScrollTopButtonEnabled,
    arrowKeySelection,
    setArrowKeySelection,
    soundEnabled,
    setSoundEnabled,
    pasteSoundEnabled,
    setPasteSoundEnabled,
    hideTrayIcon,
    setHideTrayIcon,
    hideDockIcon,
    setHideDockIcon,
    customBackground,
    setCustomBackground,
    customBackgroundOpacity,
    setCustomBackgroundOpacity,
    surfaceOpacity,
    setSurfaceOpacity,
    soundVolume,
    setSoundVolume,
    installedApps,
    appSettings,
    defaultApps,
    showAppSelector,
    dataPath,
    setAutoStart,
    setSilentStart,
    setPersistent,
    setPersistentLimitEnabled,
    setPersistentLimit,
    setDeduplicate,
    setCaptureFiles,
    setCaptureRichText,
    setRichTextSnapshotPreview,
    setDeleteAfterPaste,
    setMoveToTopAfterPaste,
    setIsRecordingRich,
    setIsRecordingSearch,
    setShowHotkeyHint,
    setIsRecording,
    isRecording,
    setTheme,
    setColorMode,
    setLanguage,
    showSourceAppIcon,
    setShowSourceAppIcon,
    setShowAppSelector,

    compactMode,
    setCompactMode,
    clipboardItemFontSize,
    setClipboardItemFontSize,
    clipboardTagFontSize,
    setClipboardTagFontSize,
    emojiPanelEnabled,
    setEmojiPanelEnabled,
    tagManagerEnabled,
    setTagManagerEnabled,
    sequentialMode,
    setSequentialModeState,
    sequentialHotkey,
    isRecordingSequential,
    setIsRecordingSequential,
  } = state;

  return {
    t,
    theme,
    language,
    colorMode,
    collapsedGroups,
    settingsSubpage,
    autoStart,
    silentStart,
    persistent,
    persistentLimitEnabled,
    persistentLimit,
    deduplicate,
    captureFiles,
    captureRichText,
    richTextSnapshotPreview,
    deleteAfterPaste,
    moveToTopAfterPaste,
    richPasteHotkey,
    isRecordingRich,
    searchHotkey,
    isRecordingSearch,
    sequentialMode,
    sequentialHotkey,
    isRecordingSequential,
    setSequentialModeState,
    setIsRecordingSequential,
    updateSequentialHotkey,
    quickPasteModifier,
    setQuickPasteModifier,
    cleanupRules,
    setCleanupRules,
    appCleanupPolicies,
    setAppCleanupPolicies,
    hotkey,
    showHotkeyHint,
    showSearchBox,
    setShowSearchBox,
    scrollTopButtonEnabled,
    setScrollTopButtonEnabled,
    arrowKeySelection,
    setArrowKeySelection,
    soundEnabled,
    setSoundEnabled,
    pasteSoundEnabled,
    setPasteSoundEnabled,
    hideTrayIcon,
    setHideTrayIcon,
    hideDockIcon,
    setHideDockIcon,
    customBackground,
    setCustomBackground,
    customBackgroundOpacity,
    setCustomBackgroundOpacity,
    surfaceOpacity,
    setSurfaceOpacity,
    soundVolume,
    setSoundVolume,
    installedApps,
    appSettings,
    defaultApps,
    showAppSelector,
    dataPath,
    toggleGroup,
    setSettingsSubpage,
    setAutoStart,
    setSilentStart,
    setPersistent,
    setPersistentLimitEnabled,
    setPersistentLimit,
    setDeduplicate,
    setCaptureFiles,
    setCaptureRichText,
    setRichTextSnapshotPreview,
    setDeleteAfterPaste,
    setMoveToTopAfterPaste,
    saveAppSetting,
    setIsRecordingRich,
    updateRichPasteHotkey,
    setIsRecordingSearch,
    updateSearchHotkey,
    setShowHotkeyHint,
    setIsRecording,
    isRecording,
    hotkeyParts,
    updateHotkey,
    setTheme,
    setColorMode,
    setLanguage,
    showSourceAppIcon,
    setShowSourceAppIcon,

    compactMode,
    setCompactMode,
    clipboardItemFontSize,
    setClipboardItemFontSize,
    clipboardTagFontSize,
    setClipboardTagFontSize,
    emojiPanelEnabled,
    setEmojiPanelEnabled,
    tagManagerEnabled,
    setTagManagerEnabled,
    checkHotkeyConflict,
    handleResetSettings,
    saveSetting,
    setShowAppSelector,
  };
};
